server:
  port: 8021

spring:
  application:
    name: score-acquire-service
  cloud:
    nacos:
      server-addr: 192.168.112.130:8840
      discovery:
        username: nacos
        password: nacos
        namespace: public
        group: ScoreCenter