server:
  port: 8026

spring:
  application:
    name: video-load-service
  cloud:
    nacos:
      server-addr: 192.168.112.130:8840
      discovery:
        username: nacos
        password: nacos
        namespace: public
        group: MediaCenter