server:
  port: 8030

spring:
  application:
    name: balance-recharge-service
  cloud:
    nacos:
      server-addr: 192.168.112.130:8840
      discovery:
        username: nacos
        password: nacos
        namespace: public
        group: PaymentCenter